-- TABLE
CREATE TABLE IF NOT EXISTS game (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    DEVELOPER VARCHAR2(30),
    PUBLISHER VARCHAR2(30),
    RELEASE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    RATING NUMBER(3)
);

-- DEFAULT ROW
INSERT OR IGNORE INTO game VALUES (1,'The Long dark', 'Hinterland Studio Inc.', 'Hinterland Studio Inc.', '2017-08-01' , 100);

-- SELECT TABLE
SELECT * FROM TABLE;