# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vgui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 570)
        MainWindow.setMinimumSize(QtCore.QSize(1040, 570))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1040, 570))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lineEdit_search = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.verticalLayout_2.addWidget(self.lineEdit_search)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.comboBox_column = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_column.setObjectName("comboBox_column")
        self.verticalLayout_2.addWidget(self.comboBox_column)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setObjectName("pushButton_search")
        self.verticalLayout_2.addWidget(self.pushButton_search)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.checkBox_insert = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_insert.setObjectName("checkBox_insert")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBox_insert)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.label_dev = QtWidgets.QLabel(self.centralwidget)
        self.label_dev.setObjectName("label_dev")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_dev)
        self.lineEdit_developer = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_developer.setObjectName("lineEdit_developer")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_developer)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        self.label_pub = QtWidgets.QLabel(self.centralwidget)
        self.label_pub.setObjectName("label_pub")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_pub)
        self.lineEdit_publisher = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_publisher.setObjectName("lineEdit_publisher")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_publisher)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setObjectName("label_date")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_date)
        self.lineEdit_release = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_release.setObjectName("lineEdit_release")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_release)
        spacerItem8 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem8)
        self.label_rating = QtWidgets.QLabel(self.centralwidget)
        self.label_rating.setObjectName("label_rating")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_rating)
        self.spinBox_rating = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_rating.setMinimum(1)
        self.spinBox_rating.setMaximum(100)
        self.spinBox_rating.setProperty("value", 100)
        self.spinBox_rating.setObjectName("spinBox_rating")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.spinBox_rating)
        self.pushButton_update = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update.setObjectName("pushButton_update")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.pushButton_update)
        self.Insert = QtWidgets.QLabel(self.centralwidget)
        self.Insert.setObjectName("Insert")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Insert)
        self.gridLayout.addLayout(self.formLayout, 1, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VGList"))
        self.label.setText(_translate("MainWindow", "Search"))
        self.pushButton_search.setText(_translate("MainWindow", "Search"))
        self.checkBox_insert.setText(_translate("MainWindow", "Yes"))
        self.label_name.setText(_translate("MainWindow", "Name"))
        self.label_dev.setText(_translate("MainWindow", "Developer"))
        self.label_pub.setText(_translate("MainWindow", "Publisher"))
        self.label_date.setText(_translate("MainWindow", "Release Date"))
        self.label_rating.setText(_translate("MainWindow", "Rating"))
        self.pushButton_update.setText(_translate("MainWindow", "Insert"))
        self.Insert.setText(_translate("MainWindow", "Insert?"))

